services:
  - type: web
    name: stancestream
    env: node
    plan: starter
    buildCommand: |
      npm install
      node setupCacheIndex.js
      node initCache.js
    startCommand: node server.js
    envVars:
      - key: REDIS_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 3000
    healthCheckPath: /api/health